### ISSUE TITLE
Front End Web UI

### ISSUE THREAD

**Issue by propagated** [propagated/Square9Analytics#16]
Express analytic data using D3.js as an engine.

- [x] #17 Update on API Get
- [x] #20 User Filter
- [x] #38 Action Selection

**Comment by propagated** [comment]
new sub-Todos:
- [ ] Make API Call
- [ ] Set up action dropdown

**Comment by propagated** [comment]
#20, #38 remaining todos to wrap this up.

**Comment by rbyrnes** [comment]
Found a nice example of implementing the User dropdown dynamically using a js data variable with jquery: http://demos.telerik.com/kendo-ui/dropdownlist/index

I'll be using this to try and create a dynamically populating list. Just in case I don't get to it in a timely fashion, I wanted to drop the example here as a reference for anyone else who wants to tackle the dropdown.

**Comment by propagated** [comment]
Core functionality complete. Remaining issues are marked for milestone 1
