### ISSUE TITLE
API doesn't return dates with zero entries

### ISSUE THREAD

**Issue by propagated** [propagated/Square9Analytics#35]
Open question:

The API only retunrs dates that the selected action occurs on. This makes the line graph look a bit interesting, as we don't have any zeroed out data being displayed. Should the API be changed to return data for each date, even if no actions occured on that date, for the sake of the graph?

**Comment by mvensel** [comment]
I would think that we would want the API to handle that somehow.

**Comment by propagated** [comment]
In thinking about it, i think the API is fine as it is. It's up to the calling application to decide if it's going to include a way of showing the dates where no action occurred, as it can assume if the date doesn't come back from the API given a period of time, there were no actions on that date.

c3's categories mode forces the current graph to have hard dates for each point with no in between. There might be a way to make c3 have more data points for the sake of scale, i just havent found it.

It's important to remember to not modify an API resource so easily just because it's inconvenient for the way you're trying to render the data. Changing an API should never be a hasty decision especially when there could be any number of apps using it.

**Comment by mvensel** [comment]
Yeah I see your point. I was just thinking of it in terms of the whole project where the goal was to create visual representations of data or generate reports based on the audit log so I was thinking that it may be beneficial for the API to always return a result regardless of the number of actions taken on a date. I do see your point about it being more flexible though.

**Comment by propagated** [comment]
In commit 47141a90d45f01f330eee6e297d203bd27482bf4 per this conversation i've changed the way the graph is rendered to a 'true' tick, meaning the x axis will now use blank space to denote time passing with no actions

this (now committed):
http://puu.sh/e73Ob/483e1b3d81.jpg

as opposed to this:

http://puu.sh/e73Wn/47e04c64e7.png


I am open for debate as to which is better.

**Comment by rbyrnes** [comment]
The 2nd option looks cleaner but the first option more accurately displays the data. 
Is there a way to add a break in the graph so that the user can see there is a lapse in time, but doesn't sacrifice the organization of the graph?

**Comment by propagated** [comment]
How about this for cleanliness: 
http://puu.sh/e76kN/9cb974b578.png

I rotated the x axis ticks

**Comment by mvensel** [comment]
That last one is the best for readability and accuracy in my opinion.

**Comment by propagated** [comment]
commit 85d0eeb1077275c938883e3e8e0f78b3a73d9f04 sets it rotated
Going with this display for now, the x axis is still a bit fiddly as the ticks don't always display a date in a heavily populated graph.

**Comment by propagated** [comment]
Reopening this per implementation of issue #38, graph looks odd with multiple lines displayed and no zero count, at least in left and right padded areas.  

See this SS: http://puu.sh/esLa5/e413f6f86e.png  

Notice how annotations updated floats, not really representing itself on the ticks where it has no data/points.

It's possible this issue would be solved by changing the graph to bars...

**Comment by propagated** [comment]
Bar graph is in. Issue now: date categories are not extending to end with multiple checkboxes checked. The date has to cover the whole x-axis.

**Comment by propagated** [comment]
posted an issue on c3's github https://github.com/masayuki0812/c3/issues/925

**Comment by propagated** [comment]
No movement yet on my issues. The workaround is to rebuild the parse function to insert 0's into the value arrays and keep the x-axis full of every returned date, or rebuild the API to return dates with zero... which i think is strictly worse. Thoughts?

**Comment by DLavoie** [comment]
I don't completely believe it, being as it can most likely be avoided, but I feel that more issues can arise from inserting values over pulling the dates.

**Comment by propagated** [comment]
this fiddle illustrates the issue
http://jsfiddle.net/propagated/1uuj8bdd/

**Comment by propagated** [comment]
So while in an earlier comment i said to generally never do this, we are going to change how the API returns data in order to resolve this bug. Closing this issue and opening another with a better description of todos.
