### ISSUE TITLE
Change API return object to date based key/value store.

### ISSUE THREAD

**Issue by propagated** [propagated/Square9Analytics#42]
This is a reform of issue #35.

In order to overcome c3 limitations having to do with x-axis labels and bar charts, we need a better way of returning data based on dates, instead of just a collection of objects of the actions themselves.

TODOS: 
- [x] Change Object model to new structure
- [x] Update API Layer to accept multiple actions in a call, and return new object struct correctly.
- [x] Update Logic Layer to accept multiple actions in a call, get the needed information out of data access, and parse them into our new object
- [x] Possibly update data access as needed (not sure)
- [ ] Change UI to make one call per request, and then load new object into chart correctly.

**Comment by propagated** [comment]
Old object model structure:
```
{
    "Users": [
        "INFINET-SYS\\pwilliams",
        "PWILLIAMS-E6430\\Square9DocuSignIntegrator",
        "PWILLIAMS-E6430\\Square9UnitTest"
    ],
    "Log": [
        {
            "Date": "2013-09-15",
            "Action": "Document Indexed"
        },
        {
            "Date": "2013-09-15",
            "Action": "Document Indexed"
        },
        {
            "Date": "2013-09-24",
            "Action": "Document Indexed"
        },
        {
            "Date": "2013-09-30",
            "Action": "Document Indexed"
        }
]
}
```

New proposed object structure:
```
{
  "Users": [
    "Pete",
    "Nick"
  ],
  "Log": {
    "2013-09-30": {
      "Document Indexed": 2,
      "Document Viewed": 0
    },
    "2013-09-15": {
      "Document Indexed": 5,
      "Document Viewed": 4
    },
    "2013-10-15": {
      "Document Indexed": 1,
      "Document Viewed": 1
    }
  }
}
```

**Comment by rbyrnes** [comment]
That looks like that's a better fit for what we need for this project.




Regards,

Bobby Byrnes
Professional Services Analyst, Square 9 Softworks
rbyrnes@square-9.com | (d) (203) 745-2743 | (c) (203) 258-6357 |
www.square-9.com

Register now <http://www.square-9.com/encompass2015> for Encompass 2015
Customer and Reseller Conference on October 20-23, 2015 at the beautiful
Sandpearl Resort in Clearwater Beach, Florida.

**Comment by propagated** [comment]
I am working on the object model and am then going to move onto logic. If anyone is picking up another aspect of this please post here.

**Comment by propagated** [comment]
Logic and objects commit coming.
No changes heavy changes to DA.

**Comment by propagated** [comment]
Updated API layer, you can now push as many 'action=' as you want in the URI.
example:
`http://localhost/square9analytics/analytics/Actions/GetData?startdate=11/15/2014&enddate=1/23/2015&action=indexed&action=viewed`

**Comment by rbyrnes** [comment]
Awesome sauce




Regards,

Bobby Byrnes
Professional Services Analyst, Square 9 Softworks
rbyrnes@square-9.com | (d) (203) 745-2743 | (c) (203) 258-6357 |
www.square-9.com

Register now <http://www.square-9.com/encompass2015> for Encompass 2015
Customer and Reseller Conference on October 20-23, 2015 at the beautiful
Sandpearl Resort in Clearwater Beach, Florida.

**Comment by propagated** [comment]
UI is updated. Everyone please take a moment to test, with this we are milestone 1 complete!
